### ISSUE TITLE
'latest' tag not available - ERROR: manifest for movim/movim:latest not found

### ISSUE THREAD

**Issue by StuartJMackintosh** [movim/movim_docker#20]
The example compose from the readme file uses the image tag 'latest' yet this is not available.

Therefore when pulling, an error is reported:
```
sudo docker-compose pull
ERROR: for movim  manifest for movim/movim:latest not found
ERROR: manifest for movim/movim:latest not found
```
Checking Docker Hub, there is no latest tag <https://hub.docker.com/r/movim/movim/tags>
The most recent tag at the time of writing is _0.14.1rc5_

A workaround is to update the image to the available tag:
Change:
`    image: movim/movim:latest`
to
`    image: movim/movim:0.14.1rc5`

The solution is to either update the example file, or use the 'latest'; tag.

**Comment by kawaii** [comment]
The documentation in general is quite poor right now as I think this project is a little too difficult for most people to get up and running in a Docker context. Even if the tag suggested in the example were correct it would still be non-functional as there is no canonical nginx configuration provided. The difficulty in releasing an easy Docker Compose solution for Movim is due to the reliance on static assets, in this case CSS and JS files that must be bind-mounted from the Movim/PHP container into the nginx container. I'm hoping that when [nginx/unit/issues/62](https://github.com/nginx/unit/issues/62) is resolved I might just be able to refactor the entire container set into one comprising nginx Unit and PHP-FPM but until then things just feel too clunky and awkward for me to let other people easily use this stack other than for experimentation purposes.
