### ISSUE TITLE
move docker config to movim repository

### ISSUE THREAD

**Issue by kskarthik** [movim/movim_docker#35]
I propose to move these dockerfiles to movim repository & integrate with github actions to build a new docker image & push it to registry on each release or commit 

@edhelas  I can take up the migration task, if this sounds good :)

**Comment by kawaii** [comment]
I'd like to keep the Docker configuration here for now - but it's more than possible for you to create a Github action on the main Movim repo that clones this repo in order to automatically create a nightly dev build.

Mainline release builds require a sha512 checksum and therefore can't be created automatically, but feel free to modify the Dockerfile to include a build argument for making nightly dev builds.

**Comment by kskarthik** [comment]
@kawaii looking at the code of Dockerfile, you are pre hasing the release binary and comparing inside the image.  In case of building on actions, do we still need hashing ?

**Comment by kskarthik** [comment]
hashing isn't required if we are building from CI, because there is no chance of tampering the release AFAIK. 

I am open for discussion on this topic
