### ISSUE TITLE
Simplify setup by removing internal Nginx container?

### ISSUE THREAD

**Issue by poVoq** [movim/movim_docker#43]
See discussion here: https://github.com/movim/movim/issues/1220

With this change: https://github.com/movim/movim/commit/c95ae5861112d9fa72d01f9c0f06d902f9db5210

I confirmed that you can directly serve the static files via the host Nginx that is needed anyways.

I think that would make the setup via Docker a bit easier.

**Comment by edhelas** [comment]
Can you please provide a Pull Request with the changes ? Then @kawaii and I can review and merge it :) ?

**Comment by poVoq** [comment]
Kawai previously mentioned they have this setup specifically for their own deployments, so I think it would be better to hear first from them if such a PR would be accepted.

**Comment by kawaii** [comment]
>I confirmed that you can directly serve the static files via the host Nginx that is needed anyways.

It's not guarantied at all that the user will have their own nginx server on the same host as their Docker/application server. It's quite common in a production environment for proxies to be on totally different hardware to the applications themselves. This is why the nginx is supplied so that the static content can be served (which php-fpm is incapable of doing itself).

Regardless, I'll soon refactor this Docker image to use nginx unit instead.

https://unit.nginx.org/
